import { styled } from "@stitches/react";
import Head from "next/head";
import { createTheme } from "../stitches.config";

const myTheme = createTheme({
  colors: {
    loContrast: "red",
  },
});

const Button = styled("button", {
  color: "$colors$loContrast",
  $$shadow: "blueviolet",
  boxShadow: "0 0 0 3px $$shadow",

  "&:hover": {
    $$shadow: "green",
  },
});

export default function Home() {
  return (
    <div>
      <Head>
        <title>Stitches Setting</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={myTheme}>
        <p>Paragraph</p>
        <span>Span</span>
        <Button>Button</Button>
      </main>
    </div>
  );
}
