import { styled } from "@stitches/react";
import Head from "next/head";
import { createTheme } from "../stitches.config";

const myTheme = createTheme({
  colors: {
    loContrast: "red",
  },
});

const FunctionalComp = (props: any) => {
  return <div {...props}></div>;
};

const Button = styled("button", {
  borderRadius: 16,
  cursor: "pointer",
  color: "$blue",

  variants: {
    color: {
      violet: {
        border: "3px solid blueviolet",

        "&:hover": {
          color: "white",
          backgroundColor: "blueviolet",
        },
      },
      green: {
        border: "3px solid green",

        "&:hover": {
          color: "white",
          backgroundColor: "green",
        },
      },
    },
  },
});

const OverridedButton = styled(Button, {
  backgroundColor: "red",
});

const OverridedFC = styled(FunctionalComp, {
  background: "red",
});

const NestWrapper = styled("div", {
  [`${Button}`]: {
    color: "white",
    background: "Blue",
  },
});

export default function Home() {
  return (
    <div>
      <Head>
        <title>Stitches Setting</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={myTheme}>
        <p>Paragraph</p>
        <span>Span</span>
        <Button>Button</Button>
        <Button color="violet">Button</Button>
        <Button color="green">Button</Button>
        <OverridedButton>Button</OverridedButton>
        <NestWrapper>
          <Button color="green">Button</Button>
        </NestWrapper>
        <OverridedFC>hello</OverridedFC>
      </main>
    </div>
  );
}
