import { styled } from "@stitches/react";
import Head from "next/head";
import { createTheme } from "../stitches.config";

const myTheme = createTheme({
  colors: {
    loContrast: "red",
  },
});

const Button = styled("button", {
  borderRadius: 16,
  cursor: "pointer",

  variants: {
    color: {
      violet: {
        border: "3px solid blueviolet",

        "&:hover": {
          color: "white",
          backgroundColor: "blueviolet",
        },
      },
      green: {
        border: "3px solid green",

        "&:hover": {
          color: "white",
          backgroundColor: "green",
        },
      },
    },
  },
});

export default function Home() {
  return (
    <div>
      <Head>
        <title>Stitches Setting</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={myTheme}>
        <p>Paragraph</p>
        <span>Span</span>
        <Button color="violet">Button</Button>
        <Button color="green">Button</Button>
      </main>
    </div>
  );
}
